# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  displayName: Install Docfx
  inputs:
    targetType: 'inline'
    script: 'choco install docfx -y'

- task: PowerShell@2
  displayName: Run Docfx
  inputs:
    targetType: 'inline'
    script: 'docfx "docfx/docfx.json"'

- task: CopyFiles@2
  displayName: Copy to Artifacts
  inputs:
    SourceFolder: 'doc'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: Publish to Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'docs'
    publishLocation: 'Container'