# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Onbox.sln'
  analyzers: 'analyzers/Onbox.Analyzers.Build.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'R2019'
  buildPath: 'src/Abstractions/bin/'

steps:
- task: NuGetToolInstaller@1
  displayName: Nuget Install

- task: NuGetCommand@2
  displayName: Nuget Restore Build Projects
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Visual Studio 2019 Build Projects
  inputs:
    solution: '$(solution)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: NuGetCommand@2
  displayName: Package .NetFramework Projects
  inputs:
    command: 'pack'
    packagesToPack: 'build/Mvc.nuspec;build/Mvc.Revit.nuspec;build/Revit.nuspec'
    versioningScheme: 'off'
    includeSymbols: true

- task: CopyFiles@2
  displayName: Copy Nuget to Staging Artifacts
  inputs:
    SourceFolder: 'build/'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: Nuget Restore Analyzers
  inputs:
    restoreSolution: '$(analyzers)'

- task: VSBuild@1
  displayName: Visual Studio 2019 Build Analyzers
  inputs:
    solution: '$(analyzers)'
    vsVersion: '16.0'
    platform: 'Any CPU'
    configuration: 'Release'
    clean: true

- task: CopyFiles@2
  displayName: Copy Analyzers Nuget to Staging Artifacts
  inputs:
    SourceFolder: 'analyzers/Onbox.Analyzers/Onbox.Analyzers.Package/bin/**'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Artifacts Publish
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'packages'