pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Onbox.sln'
  solutionFilter: 'OnboxNuget.slnf'
  analyzers: 'analyzers/Onbox.Analyzers.Build.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'R2019'

steps:

- task: PowerShell@2
  displayName: Versioning
  inputs:
    filePath: 'ren.ps1'
    arguments: '-oldNs .VDev -newNs $env:NEWNAMESPACE -oldV 0.99.99.99 -newV $env:NEWVERSION'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: NuGetToolInstaller@1
  displayName: Nuget Install

- task: NuGetCommand@2
  displayName: Nuget Restore Build Projects
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Visual Studio 2019 Build Projects
  inputs:
    solution: '$(solutionFilter)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: CmdLine@2
  displayName: Build Nuget
  inputs:
    script: nuget pack "$(Build.SourcesDirectory)/build/Onbox.Abstractions.Standard.nuspec"

- task: CopyFiles@2
  displayName: Copy Nuget to Staging Artifacts
  inputs:
    SourceFolder: 'build/'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Artifacts Publish
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'packages'
