trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projFolder: 'src/Revit.Remote.DA.Tests'
  solution: '$(projFolder)/Revit.Remote.DA.Tests.csproj'
  bundle: '$(projFolder)/revit_tests.bundle.zip'
  postman: '$(projFolder)/revit_tests.postman_collection.json'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Nuget Install

- task: CmdLine@2
  inputs:
    script: 'nuget restore $(projFolder) -OutputDirectory $(Build.SourcesDirectory)/packages'

- task: VSBuild@1
  displayName: VS Build Project
  inputs:
    solution: '$(solution)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: CopyFiles@2
  displayName: Copy package to Staging
  inputs:
    Contents: |
      $(bundle)
      $(postman)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Artifacts Publish
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'revit_tests.bundle'